services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - .env.docker:/var/www/.env
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - credit-system

networks:
    credit-system:
        driver: bridge
